### PR TITLE
All reminders display at root directory

### LINKED ISSUE #1: See All Reminders
When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.

* Each reminder should have a class of .spec-reminder-item.

* There is a failing test set up in tests/acceptance/reminder-list-test.js.

**Hot Reminder**: If you put “Closes #1” (assuming the issue is marked #1) in the pull request, your commit, or anywhere in the body of your PR, it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by DanGrund**
## Purpose
closes #1
When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page. Each reminder should have a class of .spec-reminder-item. There is a failing test set up in tests/acceptance/reminder-list-test.js.

## Approach

We set up an index route. The reminder model returns an array of reminders, brought in from mirage. we use {{each} to map over the array of reminders and post them to the page as a list with each li having a class of .spec-reminder-item

### Learning

used the turing lessons on ember routing and the ember-groceries class to figure this out as well as the ember docs getting started guide. used that same lesson to figure out the basics of mirage, and some assistance from Big Mike Z to get it all hooked up. 

### Open Questions and Pre-Merge TODOs
we have issue 2 set up and commented out. ignore that stuff plz. 

### Test coverage 

we just used the existing tests, and added descriptions so they show what they're doing semantically instead of just turing green and saying okay. 

### Merge Dependencies and Related Work

????????????????

### Follow-up tasks

- [Issue #2 ](https://github.com/turingschool-projects/1610-remember-6/issues/2)

#### Before
issue1-before

#### After
issue1-after

#### Tests
passing test

### CODE REVIEW

**Comment by DanGrund** [comment]
Oh and yeah, that's a screenshot of an empty DOM.

File: app/router.js [hunk 1]
```diff
@@ -7,6 +7,8 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
+  this.route('/');
```
Comment (Tman22) [inline app/router.js]: Why do you have this route in here? The root route will default to index.hbs / application.hbs

File: app/routes/index.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  // beforeModel(){
```
Comment (Tman22) [inline app/routes/index.js]: Don't have commented out code inside pull requests. Delete it - (even if the next issue calls for it)

File: app/routes/index.js [hunk 3]
```diff
@@ -0,0 +1,10 @@
...
+  //   this.replaceWith('/reminders')
+  // }
+  model (){
+    return this.get('store').findAll('reminder')
```
Comment (Tman22) [inline app/routes/index.js]: This should be in the reminders route

File: app/routes/reminders.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
```
Comment (Tman22) [inline app/routes/reminders.js:2]: Delete extra white space

File: app/routes/reminders.js [hunk 5]
```diff
@@ -0,0 +1,7 @@
...
+
+export default Ember.Route.extend({
+  model(){
```
Comment (Tman22) [inline app/routes/reminders.js]: See comment above ^^

File: app/templates/index.hbs [hunk 6]
```diff
@@ -0,0 +1,9 @@
+<div>hello</div>
+{{#each model as |reminder|}}
```
Comment (Tman22) [inline app/templates/index.hbs:2]: This will display all of the reminders which should be in the reminders template. Also a <ul> tag should be around the each allowing all the <li>'s to be in the <ul>

File: app/templates/reminders.hbs [hunk 7]
```diff
@@ -0,0 +1,7 @@
+<div>reminders</div>
+{{#each model as |reminder|}}
+  <li class="spec-reminder-item">
+    {{reminder}}
```
Comment (Tman22) [inline app/templates/reminders.hbs:4]: See comment above ^

File: tests/unit/routes/index-test.js [hunk 8]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
+
+moduleFor('route:index', 'Unit | Route | index', {
```
Comment (Tman22) [inline tests/unit/routes/index-test.js:3]: So most of the routes will be tested in acceptance tests. There are few occasions that you will test it by itself (see docs if you want to know more). Also just delete the useless tests

File: tests/unit/routes/reminders-test.js [hunk 9]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
+
+moduleFor('route:reminders', 'Unit | Route | reminders', {
+  // Specify the other units that are required for this test.
```
Comment (Tman22) [inline tests/unit/routes/reminders-test.js:4]: See comment above ^

File: tests/unit/models/reminder-test.js [hunk 10]
```diff
@@ -0,0 +1,12 @@
...
+
+moduleForModel('reminder', 'Unit | Model | reminder', {
+  // Specify the other units that are required for this test.
+  needs: []
+});
+
+test('it exists', function(assert) {
+  let model = this.subject();
+  // let store = this.store();
+  assert.ok(!!model);
```
Comment (Tman22) [inline tests/unit/models/reminder-test.js:11]: So this is a good start, but considering this is what it gives you I expect more. So I test that the model has a title, note, date, etc..

**Review by DanGrund — COMMENTED** [review]
Made all requested changes except testing Model attributes, which nobody in the room seems to able to help with.. ignoring for now

**Review by martensonbj — APPROVED** [review]

**Comment by martensonbj** [comment]
I'll merge this in so you can move on but keep an eye on route tests that dont need to be there. Delete those files please. Ill see what I can do about testing models help.
